//go:build integration

package cli

import (
	"context"
	"database/sql"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/dmedovich/queen"
	"github.com/dmedovich/queen/drivers/postgres"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/wait"
)

func TestAdoptGoosePostgresIntegration(t *testing.T) {
	ctx := context.Background()
	req := testcontainers.ContainerRequest{
		Image: "postgres:16-alpine", ExposedPorts: []string{"5432/tcp"},
		Env:        map[string]string{"POSTGRES_USER": "test", "POSTGRES_PASSWORD": "test", "POSTGRES_DB": "testdb"},
		WaitingFor: wait.ForLog("database system is ready to accept connections").WithOccurrence(2).WithStartupTimeout(90 * time.Second),
	}
	container, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{ContainerRequest: req, Started: true})
	if err != nil {
		if os.Getenv("QUEEN_REQUIRE_POSTGRES") == "1" {
			t.Fatalf("start PostgreSQL: %v", err)
		}
		t.Skipf("PostgreSQL container unavailable: %v", err)
	}
	defer func() { _ = container.Terminate(ctx) }()
	host, err := container.Host(ctx)
	if err != nil {
		t.Fatal(err)
	}
	port, err := container.MappedPort(ctx, "5432")
	if err != nil {
		t.Fatal(err)
	}
	db, err := sql.Open("pgx", "postgres://test:test@"+host+":"+port.Port()+"/testdb?sslmode=disable")
	if err != nil {
		t.Fatal(err)
	}
	defer func() { _ = db.Close() }()
	db.SetMaxOpenConns(1)
	if err := db.PingContext(ctx); err != nil {
		t.Fatal(err)
	}
	for _, statement := range []string{
		`CREATE TABLE goose_db_version (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version_id BIGINT NOT NULL, is_applied BOOLEAN NOT NULL)`,
		`INSERT INTO goose_db_version (version_id, is_applied) VALUES (0, true), (1, true), (2, true)`,
		`CREATE TABLE goose_adopt_body (id INT)`,
		`ALTER TABLE goose_adopt_body ADD COLUMN name TEXT`,
	} {
		if _, err := db.ExecContext(ctx, statement); err != nil {
			t.Fatal(err)
		}
	}
	registered := []queen.Migration{
		{Version: "001", Name: "create_body", UpSQL: "CREATE TABLE goose_adopt_body (id INT);"},
		{Version: "002", Name: "add_name", UpSQL: "ALTER TABLE goose_adopt_body ADD COLUMN name TEXT;"},
	}
	const sourceTable, targetTable = "goose_db_version", "queen_adopt_history"
	const sourceRef, targetRef = `"goose_db_version"`, `"queen_adopt_history"`
	plan, err := previewGooseAdoption(ctx, db, sourceTable, targetTable, sourceRef, targetRef, registered)
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.ToAdopt) != 2 {
		t.Fatalf("plan adopts %d versions, want 2", len(plan.ToAdopt))
	}
	var target sql.NullString
	if err := db.QueryRowContext(ctx, "SELECT to_regclass($1)", targetRef).Scan(&target); err != nil || target.Valid {
		t.Fatalf("preview created Queen table: %v, err = %v", target, err)
	}
	driver := postgres.NewWithTableName(db, targetTable)
	// A Goose history change invalidates the preview token before any record is written.
	if _, err := db.ExecContext(ctx, `INSERT INTO goose_db_version (version_id, is_applied) VALUES (2, false)`); err != nil {
		t.Fatal(err)
	}
	if _, err := applyGooseAdoption(ctx, driver, sourceTable, targetTable, sourceRef, targetRef, registered, plan.Fingerprint, time.Second); err == nil || !strings.Contains(err.Error(), "plan changed") {
		t.Fatalf("stale plan error = %v", err)
	}
	var count int
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM queen_adopt_history`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("records after stale plan = %d, err = %v", count, err)
	}
	if _, err := db.ExecContext(ctx, `INSERT INTO goose_db_version (version_id, is_applied) VALUES (2, true)`); err != nil {
		t.Fatal(err)
	}
	plan, err = previewGooseAdoption(ctx, db, sourceTable, targetTable, sourceRef, targetRef, registered)
	if err != nil {
		t.Fatal(err)
	}
	// A failure while writing the second version rolls back the first record too.
	if _, err := db.ExecContext(ctx, `CREATE FUNCTION fail_adoption() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.version = '002' THEN RAISE EXCEPTION 'forced failure'; END IF; RETURN NEW; END; $$`); err != nil {
		t.Fatal(err)
	}
	if _, err := db.ExecContext(ctx, `CREATE TRIGGER fail_adoption BEFORE INSERT ON queen_adopt_history FOR EACH ROW EXECUTE FUNCTION fail_adoption()`); err != nil {
		t.Fatal(err)
	}
	if _, err := applyGooseAdoption(ctx, driver, sourceTable, targetTable, sourceRef, targetRef, registered, plan.Fingerprint, time.Second); err == nil {
		t.Fatal("trigger did not abort adoption")
	}
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM queen_adopt_history`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("partial adoption records = %d, err = %v", count, err)
	}
	if _, err := db.ExecContext(ctx, `DROP TRIGGER fail_adoption ON queen_adopt_history`); err != nil {
		t.Fatal(err)
	}
	adopted, err := applyGooseAdoption(ctx, driver, sourceTable, targetTable, sourceRef, targetRef, registered, plan.Fingerprint, time.Second)
	if err != nil || adopted.AlreadyDone {
		t.Fatalf("adoption = %+v, err = %v", adopted, err)
	}
	if err := db.QueryRowContext(ctx, `SELECT count(*) FROM queen_adopt_history WHERE action = 'adopt_goose' AND status = 'success'`).Scan(&count); err != nil || count != 2 {
		t.Fatalf("adopted records = %d, err = %v", count, err)
	}
	q := queen.NewWithConfig(driver, &queen.Config{TableName: targetTable})
	for _, migration := range registered {
		q.MustAdd(migration)
	}
	if err := q.Up(ctx); err != nil {
		t.Fatalf("Queen re-executed adopted Goose migrations: %v", err)
	}
	plan, err = previewGooseAdoption(ctx, db, sourceTable, targetTable, sourceRef, targetRef, registered)
	if err != nil || !plan.AlreadyDone {
		t.Fatalf("repeat preview = %+v, err = %v", plan, err)
	}
	adopted, err = applyGooseAdoption(ctx, driver, sourceTable, targetTable, sourceRef, targetRef, registered, plan.Fingerprint, time.Second)
	if err != nil || !adopted.AlreadyDone {
		t.Fatalf("repeat adoption = %+v, err = %v", adopted, err)
	}
}
