import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  wiki: [
    'quick-start',
    {
      type: 'category',
      label: 'Use Queen',
      items: [
        'library',
        'compatibility',
        'metadata',
        'custom-drivers',
        'cli',
        'cli-reference',
        'workflows',
        'project-structure',
        'architecture',
        'migrations',
        'configuration',
        'config-files',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      items: ['examples', 'database-examples', 'goose-import', 'tap'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'support-matrix',
        'drivers',
        {
          type: 'category',
          label: 'Database Drivers',
          items: [
            'drivers/driver-postgres',
            'drivers/driver-mysql',
            'drivers/driver-sqlite',
            'drivers/driver-clickhouse',
            'drivers/driver-cockroachdb',
            'drivers/driver-mssql',
          ],
        },
        'ci-cd',
        'ci-cd-example',
        'known-limitations',
        'release-checklist',
        {type: 'category', label: 'Release Notes', items: [{type: 'autogenerated', dirName: 'releases'}]},
        'troubleshooting',
      ],
    },
  ],
};

export default sidebars;
